---
- name: Configure host.
  hosts: all
  become: true
  connection: local
  collections:
  - drew1kun.fancyfonts
  - drew1kun.shellfreak

  vars_prompt:
    - name: ssh_pass
      prompt: What is your ssh passphrase?
      private: false
      confirm: false

  pre_tasks:

    - import_tasks: tasks/gnome-settings.yml
    - import_tasks: tasks/createvars.yml
    - import_tasks: tasks/pretasks.yml 



  vars_files:
    - default.config.yml
    - config.yml

  tasks:

    - import_tasks: tasks/update.yml
    - import_tasks: tasks/base-packages.yml
    - import_tasks: tasks/swap.yml
    - import_tasks: tasks/chaotic-aur.yml
    - import_tasks: tasks/xorg.yml
    - import_tasks: tasks/amdgpu.yml
    - import_tasks: tasks/fonts.yml
    - import_tasks: tasks/gnome.yml
    - import_tasks: tasks/other-packages.yml
    - import_tasks: tasks/other-services.yml
    - import_tasks: tasks/dev-packages.yml
    - import_tasks: tasks/upgrade.yml
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/genssh.yml
    - import_tasks: tasks/kitty-theme.yml
    - import_tasks: tasks/git-config.yml
    - import_tasks: tasks/tactile.yml
    - import_tasks: tasks/ulauncher.yml



  roles:
    - role: luizgavalda.gnome_extensions
      vars:
        gnome_extension_ids:
          - 4548
    - role: terminus_powerline
      vars:
        terminus_powerline_fonts_dir: '/usr/local/share/fonts'
    - role: ohmyzsh
      vars:
        ohmyzsh_users:
          - user: "{{ lookup('env', 'USER') }}"
            theme: powerlevel10k/powerlevel10k
            ssh_ids: []
            state: present
            colorls: true




       
