---
collections:
  - community.general
  - kewlfft.aur # For AUR
  - name: drew1kun.shellfreak
    version: '*'
    type: galaxy
  - name: drew1kun.fancyfonts
roles:
  - name: luizgavalda.gnome_extensions
