- name: Register current user (workaround to change default shell)
  shell: whoami
  register: current_user

- name: Change default shell to zsh
  become: true
  shell: "chsh -s $(which zsh) {{ current_user.stdout }}"
  changed_when: false
